apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: campbellphalen@gmail.com
    privateKeySecretRef:
       name: lets-encrypt-prod
    solvers:
    - http01:
        ingress:
          class: public
