apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
  - name: config-map
    configMap:
      name: config-map
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "apt update; apt install openssh-client --assume-yes; sleep 3650d"]
    volumeMounts:
    - name: config-map
      mountPath: /template
