---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: docker.io/library/homepage-web:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homepage
  name: homepage
spec:
  ports:
    - name: homapage
      port: 80
      targetPort: 80
  selector:
    app: homepage
  type: LoadBalancer
